name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for opening your first issue in Winux! We appreciate your contribution. Someone from the team will review this shortly."
        pr-message: "Congratulations on submitting your first pull request to Winux! Your effort helps make this project better. We'll review your changes soon."
